services:
  - type: web
    name: tradingview-capture-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: TRADINGVIEW_USERNAME
        sync: false
      - key: TRADINGVIEW_PASSWORD
        sync: false
      - key: TRADINGVIEW_SESSIONID
        sync: false
    buildCommand: ""
    startCommand: ""